# -*- coding: utf-8 -*-
"""K-Nearest Neighbors Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17K1Bek-RSy0a4w96w9qi99YoAJeXI9NU

## K-Nearest Neighbors Regression
## Mini Project: Insurance Premium Prediction

---

## 1. Introduction

In the contemporary healthcare landscape, accurately estimating medical insurance premiums is crucial for both providers and policyholders. This project utilizes the Medical Cost Personal Dataset to predict individual medical charges based on demographic and health-related attributes. To achieve this, we employ the K-Nearest Neighbors (KNN) Regression algorithm.

As a non-parametric approach, KNN is particularly effective in capturing complex, non-linear patterns within healthcare data without making stringent assumptions about the underlying distribution (Altman, 1992). Our workflow encompasses comprehensive Exploratory Data Analysis (EDA), rigorous preprocessing (including feature scaling), model training, and performance evaluation using standard regression metrics such as Mean Squared Error (MSE) and R-squared ($R^2$).

---
## 2. Algorithm Explanation

What is K-Nearest Neighbors (KNN)?K-Nearest Neighbors is a non-parametric, instance-based (or "lazy") learning algorithm. Unlike eager learners, KNN does not derive a discriminative function from the training data; instead, it stores the entire dataset and performs computation during the inference phase (Fix & Hodges, 1951). In a regression context, it predicts the value of a target variable by identifying the $k$ most similar observations in the feature space.

##How Does KNN Regression Work?
The algorithm follows a structured distance-based logic to estimate continuous outcomes:

1. Selection of $k$: Define the number of neighbors to be considered.
2. Distance Calculation: For a new query point $x$, compute the distance to all points $x_i$ in the training set. The most common metric is the Euclidean distance:

$$d(x, x_i) = \sqrt{\sum_{j=1}^{n}(x_j - x_{i,j})^2}$$

3. Neighbor Identification: Select the $k$ observations with the smallest calculated distances.

4. Prediction (Aggregation): The final prediction $\hat{y}$ is typically the arithmetic mean of the neighbors' target values:

$$\hat{y} = \frac{1}{k}\sum_{i=1}^{k} y_i$$

Note: Weighted averages can also be applied where closer neighbors have a higher influence on the prediction.

---

### When Should KNN Be Used?

| Suitable Scenarios | Less Suitable Scenarios |
|---|---|
| Small-to-medium datasets | Very large datasets (slow prediction) |
| Non-linear relationships | High-dimensional data (curse of dimensionality) |
| No strong assumptions about data distribution | When interpretability is critical |
| Quick baseline models | When features are on very different scales (need scaling) |

---

### Advantages

- **Simple** to understand and implement
- **No training phase** — the model just memorises data
- **Naturally handles non-linear** decision boundaries
- **Flexible** — k and distance metric are tunable

### Limitations

- **Slow prediction** for large datasets (O(n) per query)
- **Sensitive to scale** — features must be normalised
- **Sensitive to irrelevant features** — all features are weighted equally by default
- **Memory-intensive** — stores entire training set
- **Choosing k** requires tuning; wrong k → underfitting or overfitting

##3. Exploratory Data Analysis
"""

# Core libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
from IPython.display import display

# Scikit-learn
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Aesthetics
sns.set_theme(style="whitegrid", palette="muted")
plt.rcParams.update({"figure.dpi": 120, "axes.titlesize": 13,
                     "axes.labelsize": 11, "figure.figsize": (8, 4)})
print("All libraries imported successfully.")

"""3.1 Load the Dataset"""

df = pd.read_csv("/content/insurance.csv")

df.head(10)

# Basic info :
print("=" * 55)
print("DATASET INFO")
print("=" * 55)
df.info()
print()
print("=" * 55)
print("STATISTICAL SUMMARY")
print("=" * 55)
display(df.describe())

"""#3.2 Missing Values"""

missing = df.isnull().sum()
print("Missing values per column:")
print(missing)
print(f"\nTotal missing values: {missing.sum()}")

"""#3.3 Target Variable Distribution"""

#Identify features and target variable
features_df = df.drop('expenses', axis=1)
target_df = df['expenses']
print("Features:\n", features_df)
print("Target variable:\n", target_df)

#check outliers
plt.figure(figsize=(10, 6))
sns.boxplot(data=target_df)
plt.title("Boxplot of Target Variable")
plt.show()

#remove outlires
Q1 = target_df.quantile(0.25)
Q3 = target_df.quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)
target_clean = target_df[(target_df >= lower_bound) & (target_df <= upper_bound)]

plt.figure(figsize=(10, 6))
sns.scatterplot(x = 'age', y =target_clean ,hue='sex', data = features_df)
plt.title('Age vs expenses')
plt.show()

#create a boxplot for Expenses vs Smoking Habits
plt.figure(figsize=(10, 6))
sns.boxplot(x = 'smoker', y = target_clean, data = features_df)
plt.title('Expenses vs Smoking Habits')
plt.show()

#create a scatterplot for Expenses vs BMI
plt.figure(figsize=(10, 6))
sns.scatterplot(x = 'bmi', y = target_clean, data = features_df)
plt.title('Expenses vs BMI')
plt.show()

#create a histplot for expences vs gender
plt.figure(figsize=(10, 6))
sns.histplot(data=features_df, x=target_clean, hue="sex", multiple="stack")
plt.title('Expenses vs Gender')
plt.show()

#create a boxplot for Expenses vs childern
plt.figure(figsize=(10, 6))
sns.boxplot(x = 'children', y = target_clean, data = features_df)
plt.title('Expenses vs children')
plt.show()

#create a boxplot for Expenses vs region
plt.figure(figsize=(10, 6))
sns.boxplot(x = 'region', y = target_clean, data = features_df)
plt.title('Expenses vs region')
plt.show()

"""##Data Preprocessing :

Handling missing values

Encoding categorical variables

Feature scaling (if required)
"""

#Handling missing values :
df.dropna(inplace=True)

"""Dataset has no missing values; this is a safeguard"""

# Encoding categorical variables

# Create a copy of the dataset so the original data remains unchanged
df_model = df.copy()

# Convert sex column
# female -> 0
# male   -> 1
df_model["sex"] = LabelEncoder().fit_transform(df_model["sex"])

# Convert smoker column
# no  -> 0
# yes -> 1
df_model["smoker"] = LabelEncoder().fit_transform(df_model["smoker"])

# One-Hot Encoding for region (4 categories)
# The region column has multiple categories (e.g., southeast, northwest...)
# One-Hot Encoding converts each category into a separate column with 0 or 1
df_model = pd.get_dummies(df_model, columns=["region"], drop_first=True) # drop_first=True removes one column to avoid redundancy (dummy variable trap)

# Display encoded columns
print("\nEncoded Columns:")
print(df_model.columns.tolist())

# Preview the encoded dataset
df_model.head(3)

# Define Features (X) and Target

# Features: all input variables used for prediction
X = df_model.drop("expenses", axis=1)

# Target variable: insurance cost we want to predict
y = df_model["expenses"]

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

#Feature scaling

#KNN relies on distance ; scaling is essential to prevent bias

# Initialize scaler
scaler = StandardScaler()

# Scale features so they have similar ranges
X_scaled = scaler.fit_transform(X)

"""##Model Implementation :

Train the regression model using Scikit-learn.

Example:


```
 from sklearn.linear_model import LinearRegression
```
"""

#Train/Test Split :


X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

print("Training samples:", X_train.shape)
print("Testing samples:", X_test.shape)

# Create the KNN model
# n_neighbors represents the number of nearest neighbors (K)

# Train KNN Regressor with k=5 (default)
knn_model = KNeighborsRegressor(n_neighbors=5, metric="euclidean", weights="uniform")

# Train the model using training data
knn_model.fit(X_train, y_train)

print("KNN model trained successfully.")

# Predict insurance charges using the test data
y_pred = knn_model.predict(X_test)

# Show first few predictions
print("First 10 predictions:")
print(y_pred[:10])

"""Since KNN is a distance-based algorithm, feature scaling is required to ensure that all features contribute equally to the distance calculation.

##Model Evaluation :

Evaluate the model using regression metrics:

Mean Absolute Error (MAE)

Mean Squared Error (MSE)

Root Mean Squared Error (RMSE)

R2 Score
"""

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print('MAE:', mae)
print('MSE', mse)
print('RMSE', rmse)
print('R2', r2)

"""#Bonus Challenge (Optional) :

Improve the model performance

Compare their algorithm with another regression model

Tune hyperparameters
"""

#Tune hyperparameters :

#Hyperparameter in the KNN is K(n_nieghbors) ; The number of nearest neighbors that the model relies on for prediction.

#try different value for k , to find the best

#note : small k > Overfitting
#       large k > Underfitting

rmse_values = []

k_values = range(1,21)#from 1 to 20

for k in k_values: #try each k
    model = KNeighborsRegressor (n_neighbors=k)
    model.fit(X_train, y_train)#training
    pred = model.predict(X_test)#model predict the value of insurance charges
    rmse = np.sqrt(mean_squared_error(y_test, pred))#RMSE > less is better
    rmse_values.append(rmse)#store the error for each value of K.

best_k = k_values[np.argmin(rmse_values)]#find the smallest RMSE

print("Best K value:", best_k)

"""Hyperparameter tuning was applied to find the optimal value of K. Different values from 1 to 20 were tested, and the model performance was evaluated using RMSE. The value of K that produced the lowest RMSE was selected as the optimal parameter for the KNN model.

Model Interpretation

The KNN regression model was used to predict insurance charges based on several features such as age, BMI, smoking status, and number of children.

The evaluation results show the prediction error of the model. The MAE indicates the average absolute difference between the predicted and actual insurance charges. A lower MAE means the predictions are closer to the real values.

The RMSE provides a measure of how large the prediction errors are, giving higher weight to larger errors.

The R² score shows how well the model explains the variance in the insurance charges. A higher R² value indicates that the model is better at explaining the relationship between the input features and the target variable.

Overall, the model provides a reasonable estimation of insurance costs, especially when the features are properly scaled.

---

## Scientific References (APA Style)

* **Altman, N. S. (1992).** *An Introduction to Kernel and Nearest-Neighbor Nonparametric Regression.* The American Statistician, 46(3), 175-185.
* **Description:** This paper provides a comprehensive introduction to how KNN works for regression tasks.
* **Link:** [Download PDF (via University of Washington)](https://sites.stat.washington.edu/courses/stat527/s13/readings/Altman_AmStat_1992.pdf)
* **DOI:** [10.1080/00031305.1992.10475879](https://doi.org/10.1080/00031305.1992.10475879)



---

* **Fix, E., & Hodges, J. L. (1951).** *Discriminatory Analysis: Nonparametric Discrimination: Consistency Properties.* USAF School of Aviation Medicine.
* **Description:** The foundational work that first proposed the concept of nonparametric discrimination (KNN).
* **Link:** [Access via DTIC (Digital Technical Information Center)](https://apps.dtic.mil/sti/citations/tr/ADA800276)



---

* **Bellman, R. E. (1961).** *Adaptive Control Processes: A Guided Tour.* Princeton University Press.
* **Description:** The primary source for the "Curse of Dimensionality," which is a major limitation for KNN.
* **Link:** [View on Internet Archive](https://archive.org/details/adaptivecontrolp0000rich)
* **Google Books:** [Adaptive Control Processes](https://books.google.com/books/about/Adaptive_Control_Processes.html?id=POAmAAAAMAAJ)
"""